models:
  multi_linear_regression:
    name: "Multivariate Linear Regression"
    pipeline:
      _target_: regression.MultivariateRegressionPipeline
      data_loader:
        _target_: regression.MultivariateDataLoader
        workload: "a"
        system:
          _target_: regression.LineairDBConfiguration
        feature_selector:
          _target_: regression.LassoFeatureSelector
        normalize: False
      model: 
        _target_: regression.LinearRegression
      feature_engineers:
        [  _target_: regression.LogCoreDistanceEngineer  ]
      select_features: True
      
  simple_linear_regression:
    name: "Simple Linear Regression"
    pipeline:
      _target_: regression.SimpleRegressionPipeline
      data_loader:
        _target_: regression.SimpleRegressionDataLoader
        workload: "a"
        system:
          _target_: regression.LineairDBConfiguration
        feature_selector:
          _target_: regression.LassoFeatureSelector
        normalize: True
      model: 
        _target_: regression.LinearRegression
      select_features: True
  
  gaussian_process:
    name: "Gaussian Process Linear + Matern Kernel"
    pipeline:
      _target_: regression.MultivariateRegressionPipeline
      data_loader:
        _target_: regression.MultivariateDataLoader
        workload: "a"
        system:
          _target_: regression.LineairDBConfiguration
        feature_selector:
          _target_: regression.LassoFeatureSelector
        normalize: False
      feature_engineers:
        [
          _target_: regression.NoCoreEngineer
        ]
      model: 
        _target_: regression.GaussianProcessRegressor
        kernel:
          _target_: sklearn.gaussian_process.kernels.Sum
          k1:
            _target_: sklearn.gaussian_process.kernels.DotProduct
          k2:
            _target_: sklearn.gaussian_process.kernels.Matern



data:
  train: ["result/4c6g-result.csv", "result/8c12g-result.csv"]
  target: "result/24c32g-result.csv"

sizes: [1, 5, 10, 15]

plot_design:
  _target_: regression.PlotDesign
  x_label: "Target Data Sample Size"
  y_label: "Mean Absolute Percentage Error"

plot_function: 
  _target_: regression.plot_linegraph_from_df