workload: "oltp_read_write"
feature_selector:
  _target_: regression.HandPickedFeatureSelector
  features: ["innodb_buffer_pool_size"]

datadir: ["result/mysql-64table-1Mrec-4client", "result/mysql-64table-5Mrec-4client"]
systems:
  [
    _target_: regression.MySQLConfiguration,
    _target_: regression.MySQLConfiguration
  ]

axis_label:
  _target_: regression.machine_datasize_axis_label

plot_design:
  _target_: regression.PlotDesign

plot_function: 
  _target_: regression.scatterplot_from_df