workload: "oltp_read_write"
feature_selector:
  _target_: regression.HandPickedFeatureSelector
  features: ['innodb_lru_scan_depth', 'innodb_io_capacity', 'table_open_cache']
  
datadir: ["result/mysql-64table-1Mrec-4client", "result/2-semi-sync-tbl-size-1m"]
systems:
  [
    _target_: regression.MySQLConfiguration,
    _target_: regression.MySQLReplicationConfiguration
  ]

axis_label:
  _target_: regression.machine_datasize_axis_label

plot_design:
  _target_: regression.PlotDesign

plot_function: 
  _target_: regression.scatterplot_from_df