model:
  name: "L2S Data Reuse"
  pipeline:
    _target_: regression.L2SDataReuse
    workload: "a"
    system:
      _target_: regression.LineairDBConfiguration
    base_data_path: "dataset/transfer_learning/mac/8c12g-result.csv"
    target_data_path: "dataset/transfer_learning/24c32g-result.csv"

iterations: 20

parameters: ["clients", "checkpoint_interval", "epoch_duration", "rehash_threshold", "prefetch_locality"]

data: