models:  
  proposed:
    name: "Proposed Method"
    pipeline:
      _target_: regression.Proposed
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "dataset/transfer_learning/lineairdb/mac/8c12g-result.csv"
      ref_data_path: "dataset/transfer_learning/lineairdb/mac/4c6g-result.csv"
      target_data_path: "dataset/transfer_learning/lineairdb/24c32g-result.csv"
  model_shift:
    name: "Model Shift"
    pipeline:
      _target_: regression.ModelShift
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "dataset/transfer_learning/lineairdb/mac/8c12g-result.csv"
      target_data_path: "dataset/transfer_learning/lineairdb/24c32g-result.csv"
  l2s:
    name: "L2S"
    pipeline:
      _target_: regression.L2S
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "dataset/transfer_learning/lineairdb/mac/8c12g-result.csv"
      target_data_path: "dataset/transfer_learning/lineairdb/24c32g-result.csv"  
  data_reuse:
    name: "Data Reuse"
    pipeline:
      _target_: regression.DataReuse
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "dataset/transfer_learning/lineairdb/mac/8c12g-result.csv"
      target_data_path: "dataset/transfer_learning/lineairdb/24c32g-result.csv"
  l2s_data_reuse:
    name: "L2S Data Reuse"
    pipeline:
      _target_: regression.L2SDataReuse
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "dataset/transfer_learning/lineairdb/mac/8c12g-result.csv"
      target_data_path: "dataset/transfer_learning/lineairdb/24c32g-result.csv"
  vanilla:
    name: "Baseline"
    pipeline:
      _target_: regression.Vanilla
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "dataset/transfer_learning/lineairdb/mac/8c12g-result.csv"
      target_data_path: "dataset/transfer_learning/lineairdb/24c32g-result.csv"

sizes: [5, 10, 20, 40, 60, 80, 100, 150, 200, 300, 400]

num_trial: 5

plot_design:
  _target_: regression.PlotDesign
  x_label: "Target Data Sample Size"
  y_label: "Mean Absolute Percentage Error"

plot_function: 
  _target_: regression.plot_linegraph_from_df