models:  
  proposed:
    name: "Proposed Method"
    pipeline:
      _target_: regression.Proposed
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "result/mac/8c12g-result.csv"
      ref_data_path: "result/mac/4c6g-result.csv"
      target_data_path: "result/24c32g-result.csv"
  ToyChimera:
    name: "ToyChimera"
    pipeline:
      _target_: regression.ToyChimera
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "result/mac/8c12g-result.csv"
      ref_data_path: "result/mac/4c6g-result.csv"
      target_data_path: "result/24c32g-result.csv"
  vanilla:
    name: "Baseline"
    pipeline:
      _target_: regression.Vanilla
      workload: "a"
      system:
        _target_: regression.LineairDBConfiguration
      base_data_path: "result/mac/8c12g-result.csv"
      target_data_path: "result/24c32g-result.csv"

sizes: [5, 10, 20, 40, 60, 80, 100, 150, 200, 300, 400]

num_trial: 5

plot_design:
  _target_: regression.PlotDesign
  x_label: "Target Data Sample Size"
  y_label: "Mean Absolute Percentage Error"

plot_function: 
  _target_: regression.plot_linegraph_from_df